stages:
  - test

test:
  image: node:latest
  stage: test
  script:
    # install dependencies
    - yarn ci
    # start the server in the background
    - yarn start:ci &
    # run Cypress tests
    - yarn cy:run
