stages:
  - test

test:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  script:
    # install dependencies
    - yarn ci
    - yarn start:ci &
    # run Cypress tests
    - yarn cy:run
