import type { NextPage } from "next";
import Head from "next/head";
import React, { FunctionComponent } from "react";

import { css, ThemeProvider } from "@emotion/react";
import {
	Alert,
	Autocomplete,
	Button,
	ClassNameMap,
	Paper,
	PaperClasses,
	styled,
	Theme,
} from "@mui/material";
import { makeStyles } from "@mui/styles";
import Counter from "@/components/Counter";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Counter />
      
		</div>
	);
};

export default Home;
